#! /bin/sh

# The goal of this file is to write the branches prefix into the commit message

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

parse_branch_name () {
  local branch=$(git branch --show-current)
  grep -o "\(SKVAD-\d*\)" <<< $branch
}

prepare_commit_msg () {
 local jira_id=$(parse_branch_name)
 local new_message="[${jira_id}]"

 if [ -z $jira_id ]
 then
   echo "\nThere is no jira id in the branch name, not adding to commit message\n"
 elif [[ $(grep "\[SKVAD-.*\]" $COMMIT_MSG_FILE) ]]
 then
   echo "\nThere is already a jira id in the commit message\n"
 else
   sed -i.bak -e "1s/^/${new_message} /" $COMMIT_MSG_FILE
 fi
}

prepare_commit_msg
